site_name: Python Banyan
pages:
    - User's Guide: index.md
    - Additional Required Software:
      - Python 3 Installation: python3_install.md
      - ZeroMQ Installation: zmq_install.md
      - Python Banyan Installation: banyan_install.md
      - Lunch Launcher Installation: lunch_install.md
      - Remi GUI Library: remi_install.md
    - About: about.md
theme: readthedocs
